### create BOOK
POST localhost:8081/book/save
Content-Type: application/json

{
  "name": "Bahor keldi seni so`roqlab",
  "language": "UZB",
  "price": 100,
  "attachID": "http://old.xushnudbek.uz/wp-content/uploads/2016/02/yillik-reyting-kitob-1.jpg",
  "author": "Zulfiya"
}